# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: "MasterPipelineTest"

trigger:
  - master

pool:
  vmImage: "macOS-latest"

stages:
  - stage: SetupEnvironment
    jobs:
      - job: SetupNode
        steps:
          - script: echo "Setup Node"
  - stage: CleanEnvironment
    dependsOn: SetupEnvironment
    jobs:
      - job: CleanJS
        steps:
          - script: echo "rm -rf node_modules yarn.lock"

      - job: CleanAndroid
        dependsOn: CleanJSData
        steps:
          - script: echo "cd android && ./gradlew clean"

      - job: CleanIOS
        steps:
          - script: echo "cd ios && rm -rf Pods Podfile.lock"

  - stage: InstallDependncies
    dependsOn: [SetupEnvironment, CleanEnvironment]
    jobs:
      - job: JS
        steps:
          - script: yarn
      - job: iOS
        dependsOn: JS
        steps:
          - script: echo "cd ios && pod install"

  - stage: BuildAndDeployOnAppCenter
    dependsOn: [SetupEnvironment, CleanEnvironment, InstallDependncies]
    jobs:
      - job: Android
        steps:
          - script: echo "Deploying Android Pointing To Integ!"
          - script: echo "Deploying Android Pointing To Preprod!"
      - job: iOS
        steps:
          - script: echo "Deploying iOS Pointing To Integ!"
          - script: echo "Deploying iOS Pointing To Preprod!"
