# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

name: "MasterPipelineTest"

trigger:
  - master

pool:
  vmImage: "macOS-10.156"

stages:
  - stage: SetupEnvironment
    displayName: "Install necessary tools."
    jobs:
      - job: SetupNode
        displayName: "Install Node"
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: "12.14.1"
      - job: SetupYarn
        displayName: "Install Yarn"
        steps:
          - script: npm install -g yarn@1.21.1
  - stage: CleanEnvironment
    displayName: "Remove old data"
    jobs:
      - job: CleanJSData
        displayName: "Remove node_modules and yarn.lock"
        steps:
          - script: rm -rf node_modules yarn.lock
      - job: CleanAndroid
        displayName: "Cleand Android Build"
        steps:
          - script: cd android && ./gradlew clean && cd ..
      - job: CleanIOS
        displayName: "Cleand iOS Build"
        steps:
          - script: cd ios && rm -rf Pods Podfile.lock && cd ..
  - stage: InstallDependncies
    displayName: "Install all dependencies"
    jobs:
      - job: YarnAndPodInstall
        displayName: "Install JS and iOS Dependencies"
        steps:
          - script: yarn
          - script: cd ios && pod install
  - stage: BuildAndDeployOnAppCenter
    displayName: "Build Apps and distribute on AppCenter"
    jobs:
      - job: Android
        steps:
          - script: echo Deploying Android Pointing To Integ!
          - script: echo Deploying Android Pointing To Preprod!
      - job: iOS
        steps:
          - script: echo Deploying iOS Pointing To Integ!
          - script: echo Deploying iOS Pointing To Preprod!
